# Generated by Django 2.2.4 on 2019-08-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190827_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price_extras',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
