# Generated by Django 2.2.4 on 2019-08-29 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_item_price_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='position',
            field=models.IntegerField(default=1000000),
        ),
    ]
